/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.knowledge.horus.views;

/**
 *
 * @author Kallel
 */
public class SaidaCCtoCME extends javax.swing.JFrame {

    /**
     * Creates new form Recebimento
     */
    public SaidaCCtoCME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConteúdo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonDefeito = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonConcluir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableItens = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldIDCaixa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEspecialidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIDIntrumental = new javax.swing.JTextField();
        jTextFieldDescrição = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldItensRestantes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recebimento de Material Sujo");
        setResizable(false);
        getContentPane().setLayout(null);

        jTableConteúdo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ));
        jTableConteúdo.setEnabled(false);
        jTableConteúdo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableConteúdo);
        if (jTableConteúdo.getColumnModel().getColumnCount() > 0) {
            jTableConteúdo.getColumnModel().getColumn(0).setMinWidth(90);
            jTableConteúdo.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTableConteúdo.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(840, 90, 450, 560);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Conteúdo da Caixa:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(840, 60, 450, 30);

        jButtonDefeito.setText("Informar instrumental com defeito");
        jButtonDefeito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDefeito.setMaximumSize(new java.awt.Dimension(80, 25));
        jButtonDefeito.setMinimumSize(new java.awt.Dimension(80, 25));
        jButtonDefeito.setPreferredSize(new java.awt.Dimension(80, 25));
        jButtonDefeito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefeitoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDefeito);
        jButtonDefeito.setBounds(10, 470, 360, 30);

        jButtonCancelar.setText("Cancelar saída");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(10, 510, 360, 30);

        jButtonConcluir.setText("Concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConcluir);
        jButtonConcluir.setBounds(10, 550, 360, 30);

        jTableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ));
        jTableItens.setEnabled(false);
        jTableItens.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableItens);
        if (jTableItens.getColumnModel().getColumnCount() > 0) {
            jTableItens.getColumnModel().getColumn(0).setMinWidth(90);
            jTableItens.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTableItens.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(380, 90, 450, 560);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ítens acrescentados");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 60, 450, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);
        jPanel2.add(jTextFieldIDCaixa);
        jTextFieldIDCaixa.setBounds(130, 10, 220, 20);

        jLabel1.setText("Código de barras:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 20);

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.setFocusable(false);
        jPanel2.add(jTextFieldNome);
        jTextFieldNome.setBounds(130, 40, 220, 20);

        jTextFieldEspecialidade.setEnabled(false);
        jPanel2.add(jTextFieldEspecialidade);
        jTextFieldEspecialidade.setBounds(130, 70, 220, 20);

        jLabel3.setText("Especialidade:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 70, 110, 20);

        jLabel4.setText("Nome da caixa:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 40, 110, 20);

        jLabel12.setText("Status:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 100, 110, 20);

        jTextFieldStatus.setEnabled(false);
        jPanel2.add(jTextFieldStatus);
        jTextFieldStatus.setBounds(130, 100, 220, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 90, 360, 130);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel6.setText("Código datamatrix:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 10, 110, 20);

        jTextFieldIDIntrumental.setEnabled(false);
        jPanel1.add(jTextFieldIDIntrumental);
        jTextFieldIDIntrumental.setBounds(120, 10, 230, 20);

        jTextFieldDescrição.setEnabled(false);
        jTextFieldDescrição.setFocusable(false);
        jPanel1.add(jTextFieldDescrição);
        jTextFieldDescrição.setBounds(10, 50, 340, 20);

        jLabel7.setText("Descrição:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 30, 70, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 280, 360, 80);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Caixa:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 60, 360, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Instrumental:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 250, 360, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ítens Restantes");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(110, 410, 130, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Saída de material para a CME");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 0, 400, 50);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(null);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1300, 50);

        jTextFieldItensRestantes.setEditable(false);
        jTextFieldItensRestantes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextFieldItensRestantes.setEnabled(false);
        jTextFieldItensRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItensRestantesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldItensRestantes);
        jTextFieldItensRestantes.setBounds(10, 390, 90, 60);

        setSize(new java.awt.Dimension(1316, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldItensRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItensRestantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItensRestantesActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonDefeitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefeitoActionPerformed
        //DanificadoInstru Danificado = new DanificadoInstru();
        //Danificado.setVisible(true);
    }//GEN-LAST:event_jButtonDefeitoActionPerformed

    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaCCtoCME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaCCtoCME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaCCtoCME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaCCtoCME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaCCtoCME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JButton jButtonDefeito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableConteúdo;
    private javax.swing.JTable jTableItens;
    private javax.swing.JTextField jTextFieldDescrição;
    private javax.swing.JTextField jTextFieldEspecialidade;
    private javax.swing.JTextField jTextFieldIDCaixa;
    private javax.swing.JTextField jTextFieldIDIntrumental;
    private javax.swing.JTextField jTextFieldItensRestantes;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
